apiVersion: v1
kind: Service
metadata:
  name: poddns-admission-webhook
  labels:
    app: poddns-admission-webhook
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: poddns-admission-webhook